version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://backend:4000/api
    ports:
      - '3000:80'
    depends_on:
      - backend
    environment:
      # When running via docker-compose we prefer the internal service URL
      - VITE_API_BASE_URL=http://backend:4000/api
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - '4000:4000'
    environment:
      # Use the local mongo service when running compose
      - MONGO_URL=mongodb://mongo:27017/ideaboard
      - PORT=4000
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
